# Generated by Django 6.0.7 on 2026-07-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('founded_year', models.IntegerField(default=2022)),
                ('stage', models.CharField(default='Series A', max_length=50)),
                ('revenue', models.CharField(default='$50.0K/mo', max_length=50)),
                ('growth', models.CharField(default='+15.0%', max_length=50)),
                ('team_size', models.IntegerField(default=10)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('valuation', models.CharField(default='$10.0M', max_length=50)),
                ('active_users', models.IntegerField(default=5000)),
                ('score', models.IntegerField(default=85)),
                ('innovation_score', models.IntegerField(default=80)),
                ('investor_interest_score', models.IntegerField(default=82)),
                ('market_trend_score', models.IntegerField(default=84)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(default='AI, SaaS, B2B', max_length=255)),
                ('tech_stack', models.CharField(default='React, Python, PostgreSQL, AWS', max_length=255)),
                ('target_audience', models.CharField(default='Enterprise Clients', max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('summary', models.TextField()),
                ('details_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FOUNDER', 'Founder'), ('INVESTOR', 'Investor'), ('ADMIN', 'Admin')], default='FOUNDER', max_length=20)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('firm', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='api.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'startup')},
            },
        ),
    ]
