# Generated by Django 6.0.6 on 2026-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meetingrequest_investor_startup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='founder_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
