# Generated by Django 6.0.6 on 2026-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_founder_reply_to_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='investor_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
