# Generated by Django 6.0.6 on 2026-08-05 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_investor_reply_to_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firm', models.CharField(blank=True, max_length=200, null=True)),
                ('investor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('firm_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thesis', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('industries', models.TextField(blank=True, null=True)),
                ('stages', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('min_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('max_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_size', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolio_size', models.IntegerField(default=0)),
                ('portfolio', models.TextField(blank=True, null=True)),
                ('exits', models.IntegerField(default=0)),
                ('total_deals', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
